/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngotest;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Marcu
 */
public class LaggTillEllerBortHandLaggare extends javax.swing.JFrame {

    /**
     * Creates new form LaggTillEllerBortPartner
     */
    public LaggTillEllerBortHandLaggare(InfDB idb, String aid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
    }
    private static InfDB idb;
    private static String aid;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjektIDRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        HandlaggareIDRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LaggTillKnapp = new javax.swing.JButton();
        TaBortKnapp = new javax.swing.JButton();
        TillbakaKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Projekt ID:");

        jLabel2.setText("HandLäggare:ID");

        LaggTillKnapp.setText("Lägg till");
        LaggTillKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaggTillKnappActionPerformed(evt);
            }
        });

        TaBortKnapp.setText("Ta bort");
        TaBortKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaBortKnappActionPerformed(evt);
            }
        });

        TillbakaKnapp.setText("Tillbaka");
        TillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LaggTillKnapp)
                                .addGap(18, 18, 18)
                                .addComponent(TaBortKnapp))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HandlaggareIDRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ProjektIDRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TillbakaKnapp)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjektIDRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HandlaggareIDRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LaggTillKnapp)
                    .addComponent(TaBortKnapp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(TillbakaKnapp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaKnappActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ProjektchefMeny(idb, aid).setVisible(true);
    }//GEN-LAST:event_TillbakaKnappActionPerformed

    private void LaggTillKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaggTillKnappActionPerformed
        // TODO add your handling code here:
        LaggTillHandlaggare();
    }//GEN-LAST:event_LaggTillKnappActionPerformed

    private void TaBortKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaBortKnappActionPerformed
        // TODO add your handling code here:
        TaBortHandlaggare();
    }//GEN-LAST:event_TaBortKnappActionPerformed

    public void LaggTillHandlaggare(){
        if(ValideringsKlass.textFaltHarVarde(ProjektIDRuta)){
            if(ValideringsKlass.textFaltHarVarde(HandlaggareIDRuta)){
                if(ValideringsKlass.idKontroll(ProjektIDRuta)){
                     if(ValideringsKlass.idKontroll(HandlaggareIDRuta)){
                         if(ValideringsKlass.behorighetProjektChefForProjekt(idb, aid, ProjektIDRuta)){
                            if(ValideringsKlass.KontrolleraHandlaggareFinns(idb, aid, HandlaggareIDRuta)){
                             String projektID = ProjektIDRuta.getText();
                             String HandlaggareID = HandlaggareIDRuta.getText();
                             try {
                                 String Fraga = ("Insert into ans_proj (pid, aid) values ('" + projektID + "', '" + HandlaggareID + "')");
                                 idb.insert(Fraga);
                                 JOptionPane.showMessageDialog(null, "Ny handläggare tillagd!");
                             }
                              catch (InfException ex){
                              System.out.println(ex.getMessage());
                              }    
                         }
                     }
                   }
                }
            }
        }
    }
    
    public void TaBortHandlaggare(){
        if(ValideringsKlass.textFaltHarVarde(ProjektIDRuta)){
            if(ValideringsKlass.textFaltHarVarde(HandlaggareIDRuta)){
                if(ValideringsKlass.idKontroll(ProjektIDRuta)){
                     if(ValideringsKlass.idKontroll(HandlaggareIDRuta)){
                         if(ValideringsKlass.behorighetProjektChefForProjekt(idb, aid, ProjektIDRuta)){
                             String projektID = ProjektIDRuta.getText();
                             String HandlaggareID = HandlaggareIDRuta.getText();
                             if(ValideringsKlass.KontrolleraAns_ProjektFinns(idb, aid, ProjektIDRuta, HandlaggareIDRuta)){
                             try{
                             String Fraga = ("Delete from ans_proj where pid = '" + projektID + "' and aid = '" + HandlaggareID + "'");
                             idb.delete(Fraga);
                             JOptionPane.showMessageDialog(null, "HandLaggare borttagen!");
                              }
                             catch (InfException ex){
                              System.out.println(ex.getMessage());
                            }     
                          }
                        }
                    }
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillEllerBortHandLaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillEllerBortHandLaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillEllerBortHandLaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillEllerBortHandLaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new LaggTillEllerBortPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HandlaggareIDRuta;
    private javax.swing.JButton LaggTillKnapp;
    private javax.swing.JTextField ProjektIDRuta;
    private javax.swing.JButton TaBortKnapp;
    private javax.swing.JButton TillbakaKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
