/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngotest;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Thomas
 */
public class ProjektchefMeny extends javax.swing.JFrame {
ArrayList<HashMap<String, String>> ProjektChefUppgifter = new ArrayList<>();
    /**
     * Creates new form ProjektchefMeny
     */
    public ProjektchefMeny(InfDB idb, String aid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        fyllStatistik();
        hamtaAllaData();
        fyllProjektChefTabel();
    }

    private static InfDB idb;
    private static String aid;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTillbakaKnapp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AvgKostnadRuta = new javax.swing.JTextField();
        LägstKostnadRuta = new javax.swing.JTextField();
        HögstKostnadRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProjektchefTabell = new javax.swing.JTable();
        RedigeraKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTillbakaKnapp.setText("Tillbaka");
        jTillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTillbakaKnappActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Projektchefs meny");

        AvgKostnadRuta.setEditable(false);

        LägstKostnadRuta.setEditable(false);

        HögstKostnadRuta.setEditable(false);

        jLabel2.setText("Snittkostnad");

        jLabel3.setText("Lägst kostnad");

        jLabel4.setText("Högst kostnad");

        ProjektchefTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Projekt ID", "Projektnamn", "Beskrivning", "Startdatum", "Slutdatum", "Kostnad", "Status", "Prioritet", "Land"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProjektchefTabell);
        if (ProjektchefTabell.getColumnModel().getColumnCount() > 0) {
            ProjektchefTabell.getColumnModel().getColumn(0).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(1).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(2).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(3).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(4).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(5).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(6).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(7).setResizable(false);
            ProjektchefTabell.getColumnModel().getColumn(8).setResizable(false);
        }

        RedigeraKnapp.setText("Ändra uppgifter");
        RedigeraKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedigeraKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTillbakaKnapp)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AvgKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LägstKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HögstKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RedigeraKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AvgKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LägstKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HögstKostnadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RedigeraKnapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jTillbakaKnapp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTillbakaKnappActionPerformed
        setVisible(false);
        new InfoRuta(idb, aid).setVisible(true);
    }//GEN-LAST:event_jTillbakaKnappActionPerformed

    private void RedigeraKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedigeraKnappActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AndraProjektSomChefRuta(idb, aid).setVisible(true);
    }//GEN-LAST:event_RedigeraKnappActionPerformed

    private void fyllStatistik()
    {
        try {
        String avgFraga = ("Select round(avg(kostnad),2) from projekt where projektchef = '" + aid + "'");
        String minFraga = ("Select round(min(kostnad),2) from projekt where projektchef = '" + aid + "'");
        String maxFraga = ("Select round(max(kostnad),2) from projekt where projektchef = '" + aid + "'");
        
        String avgKostnad = idb.fetchSingle(avgFraga);
        String minKostnad = idb.fetchSingle(minFraga);
        String maxKostnad = idb.fetchSingle(maxFraga);
        
        AvgKostnadRuta.setText(avgKostnad);
        LägstKostnadRuta.setText(minKostnad);
        HögstKostnadRuta.setText(maxKostnad);
        }
        catch (InfException ex){
            System.out.println(ex.getMessage());
        }
    }
    
     public void hamtaAllaData(){
        try{
            String fraga = ("Select pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, status, prioritet, land from projekt where projektchef = '" + aid +"'");
            ProjektChefUppgifter = idb.fetchRows(fraga);
        }
        catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }
      public void fyllProjektChefTabel(){
        
        DefaultTableModel model1 = (DefaultTableModel) ProjektchefTabell.getModel();
        model1.setRowCount(0);
        for(HashMap<String, String> projekt : ProjektChefUppgifter){
            String[] data = new String [model1.getColumnCount()];
            data[0] = projekt.get("pid");
            data[1] = projekt.get("projektnamn");
            data[2] = projekt.get("beskrivning");
            data[3] = projekt.get("startdatum");
            data[4] = projekt.get("slutdatum");
            data[5] = projekt.get("kostnad");
            data[6] = projekt.get("status");
            data[7] = projekt.get("prioritet");
            data[8] = projekt.get("land");
            model1.addRow(data);
        }
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ProjektchefMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AvgKostnadRuta;
    private javax.swing.JTextField HögstKostnadRuta;
    private javax.swing.JTextField LägstKostnadRuta;
    private javax.swing.JTable ProjektchefTabell;
    private javax.swing.JButton RedigeraKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTillbakaKnapp;
    // End of variables declaration//GEN-END:variables
}
