/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngotest;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author eriks
 */
public class SeAllaPersonalAvdelning extends javax.swing.JFrame {
        private static InfDB idb;
        private String aid;
    /**
     * Creates new form SeAllaPersonalAvdelning
     */
    public SeAllaPersonalAvdelning(InfDB idb, String aid) {
       initComponents();
        this.idb = idb;
        this.aid = aid;
        listaPersonal();
    }

    private void listaPersonal(){
        try {
            String avdelningQuery = "SELECT avdelning FROM anstalld WHERE aid = '" + aid + "'";
            String avdelning = idb.fetchSingle(avdelningQuery);
            
            if(avdelning != null) {
                String personalQuery = "SELECT fornamn FROM anstalld WHERE avdelning =" + avdelning;
                List<String> personalLista = idb.fetchColumn(personalQuery);
                
                if(personalLista != null){
                    for(String fornamn : personalLista) {
                        personal.append(fornamn + "\n");
                    }
                } else {
            JOptionPane.showMessageDialog(this, "ingen personal hittades");// varje if sats måste ha en egen else så man vet vart felet är
                }
            } else{
                JOptionPane.showMessageDialog(this, "ingen avdelning hittades"); // varje if sats måste ha en egen else så man vet vart felet är
            }
          }catch (InfException A){
            JOptionPane.showMessageDialog(this, "Fel i databasen" + A.getMessage());
        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personal = new javax.swing.JTextArea();
        personalRubrik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personal.setColumns(20);
        personal.setRows(5);
        jScrollPane1.setViewportView(personal);

        personalRubrik.setText("Här är all personal på avdelningen");
        personalRubrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalRubrikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(personalRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(personalRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void personalRubrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalRubrikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalRubrikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeAllaPersonalAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeAllaPersonalAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeAllaPersonalAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeAllaPersonalAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SeAllaPersonalAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea personal;
    private javax.swing.JTextField personalRubrik;
    // End of variables declaration//GEN-END:variables

    
}
